### ISSUE TITLE
Milestone 3 feedback

### ISSUE THREAD

**Issue by GiuseppeTT** [DSCI-310/DSCI-310-Group-3#116]
## Rubric
- 25 / 25: Analysis code is abstracted to four (or more) scripts which take command line arugments and save analysis artifacts (e.g., figures and data for tables).
- 25 / 25: Report is written in a literate code document, and the code in the literate code document primarily functions to source analysis artifacts and format the document.
- 23 / 25: A data analysis pipeline written in GNU Make exists, and works to run the analysis from beginning to end, as well as to clean up the analysis
- 2 / 2: Dependencies have been updated (so it include the test libraries)
- 1 / 2: Project file and directory structure organization
- 2 / 2: GitHub Project board
- 2 / 2: GitHub Issue Milestones
- 2 / 2: Follows GitHub flow version control workflow
- 1 / 2: GitHub release
- 8 / 13: Analysis can be run reproducibly using documentation provided in the README.

## Commonly provided feedback

Recommended to open an issue in the project's repository to provide this feedback so students can act on it.
In milestone 4, these things will be regraded as part of the final grade for the project.
Bolded points indicate how many points should be taken off the rubric for each of these.
These numbers do not need to be included in the GitHub issue.

Text to copy and paste into GitHub issue before providing specific comments:

*Congratulations on finishing milestone 2! We can see you put a lot of work into this project, nice work!
Below we list some specific feedback you can use to improve your project.
We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
If anything is unclear, please feel free to ask questions in this issue thread.*

### A data analysis pipeline written in GNU Make exists, and works to run the analysis from beginning to end, as well as to clean up the analysis

- [ ] Target `all` could be simplified by writing something like `all: <report_target>`. **- 2**

### Project file and directory structure organization

- [ ] There are folder/files that should not be committed. **- 1**

`src/__pycache__`

### GitHub release

- [ ] Please provide the link to the release as `https://github.com/DSCI-310/REPOSITORY/tree/VERSION` (replacing `REPOSITORY` and `VERSION` with the correct ones for your project version for each milestone). This makes is a lot easier for someone to just visit the repository as it was at that point in the project's history. **-1**

###  Analysis can be run reproducibly using documentation provided in the README

- [ ] I could not reproduce the analysis because I got an error. **- 5**

I got the following error when executing `make all`. The way I understand, the cloned repository does not contain a `data/` folder and the makefile does not create one either when missing.

```
(base) jovyan@417aee42fd63:~/work/DSCI-310-Group-3$ make all
python ./src/download_data.py https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data ./data/adult.data
Traceback (most recent call last):
  File "/home/jovyan/work/DSCI-310-Group-3/./src/download_data.py", line 39, in <module>
    data.to_csv(path)
  File "/opt/conda/lib/python3.9/site-packages/pandas/core/generic.py", line 3563, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/opt/conda/lib/python3.9/site-packages/pandas/io/formats/format.py", line 1180, in to_csv
    csv_formatter.save()
  File "/opt/conda/lib/python3.9/site-packages/pandas/io/formats/csvs.py", line 241, in save
    with get_handle(
  File "/opt/conda/lib/python3.9/site-packages/pandas/io/common.py", line 697, in get_handle
    check_parent_directory(str(handle))
  File "/opt/conda/lib/python3.9/site-packages/pandas/io/common.py", line 571, in check_parent_directory
    raise OSError(fr"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: 'data'
make: *** [Makefile:6: data/adult.data] Error 1
```
