### ISSUE TITLE
Milestone 4 feedback

### ISSUE THREAD

**Issue by GiuseppeTT** [DSCI-310/DSCI-310-Group-3#117]
*Congratulations on finishing your final project!!! This is a great accomplishment and you should be proud!
Below we list some specific feedback you can use to improve your project if you so desire,
but most importantly to learn.
We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
If anything is unclear, please feel free to ask questions in this issue thread.*

### The software package is well documented

- [ ] It is missing vignette/tutorials docs. **- 1**

- [ ] There are incorrect instructions. **- 1**

I could not install the group package using the instructions provided.

### Dependencies have been updated (so it include the newly created external software package)

- [ ] Dependencies have been updated but are not in the final image. **- 0.5**

### Project file and directory structure organization

- [ ] There are folder/files that should not be committed. **- 0.5**

`src/__pycache__/`

### GitHub release

- [ ] Please provide the link to the release as `https://github.com/DSCI-310/REPOSITORY/tree/VERSION` (replacing `REPOSITORY` and `VERSION` with the correct ones for your project version for each milestone). This makes is a lot easier for someone to just visit the repository as it was at that point in the project's history. **-.5**

###  Analysis can be run reproducibly using documentation provided in the README

- [ ] I got an error while trying to run `make all`. **- 2.5**

```
(base) jovyan@bea211032906:~/work/DSCI-310-Group-3$ make all
python ./src/download_data.py https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data ./data/adult.data
python ./src/process_data.py data/adult.data
Traceback (most recent call last):
  File "/home/jovyan/work/DSCI-310-Group-3/./src/process_data.py", line 21, in <module>
    from group3package.remove_column import remove_column as rc
ModuleNotFoundError: No module named 'group3package'
make: *** [Makefile:10: data/adult.data_unprocessed.data] Error 1
```

- [ ] I got an error while trying to install the group package. **- 2.5**

```
(base) jovyan@bea211032906:~/work/DSCI-310-Group-3$ pip install group3package
ERROR: Could not find a version that satisfies the requirement group3package (from versions: none)
ERROR: No matching distribution found for group3package
```
