### ISSUE TITLE
Milestone 2 feedback

### ISSUE THREAD

**Issue by GiuseppeTT** [DSCI-310/DSCI-310-Group-3#64]
*Congratulations on finishing milestone 2! We can see you put a lot of work into this project, nice work!
Below we list some specific feedback you can use to improve your project.
We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
If anything is unclear, please feel free to ask questions in this issue thread.*

### Code is abstracted to functions with good function design

- [ ] There are cases of functions that do not check for proper input and/or do not provide useful error messages. **- 3**

`filter`, `regression` and `remove_column`.

### Helper data for tests is tractable and reproducible

- [ ] There are some complex values that could be replaced by simpler values + some kind of `expect_approximate` test function. **- 1**

`regression`

### Tests are written for each function, and work expected

- I ran the tests and got an error. ** - 3**

```
========================================================================== ERRORS ===========================================================================
_________________________________________________________ ERROR collecting tests/test_regression.py _________________________________________________________
tests/test_regression.py:17: in <module>
    assert expected.equals(results)
E   assert False
E    +  where False = <bound method NDFrame.equals of               0\n0  2.000000e+00\n1  1.256074e-15>(              0\n0  2.000000e+00\n1  2.050323e-15)
E    +    where <bound method NDFrame.equals of               0\n0  2.000000e+00\n1  1.256074e-15> =               0\n0  2.000000e+00\n1  1.256074e-15.equals
===================================================================== warnings summary ======================================================================
Python/remove_column.py:18
Python/remove_column.py:18
  /home/giuseppett/Downloads/DSCI-310-Group-3/Python/remove_column.py:18: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
    return df.drop(column_name, 1, inplace=False)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
================================================================== short test summary info ==================================================================
ERROR tests/test_regression.py - assert False
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=============================================================== 2 warnings, 1 error in 0.35s ================================================================
```

### Tests are well documented

- [ ] There is no documentation. It is not clear what the tests are testing. **- 5**

Consider using `pytest` and its features to document what the tests are doing.

### Tests suite is of high quality

- [ ] There are cases of functions that do not test at least 2 expected input. **- 0.5**

`regression`

- [ ] There are cases of functions that do not test at least 1 edge-case input. **- 1**

`regression`

- [ ] There are cases of functions that do not test at least 1 wrong input. **- 3**

`filter`, `regression` and `remove_column`

### Project file and directory structure organization

- [ ] Project does not use `src/` for saving files containing user-defined functions. **- 1**

###  Analysis can be run reproducibly using documentation provided in the README

- [ ] Clearly specify usage instructions to the point a user could copy and paste them and they would work. If a specific value needs to be inserted (e.g., volume mounting, port forwarding, tag version - which should be specified, as relying on latest is unreliable for many reasons, etc) suggest the most reasonable value and provide the list (or link to a list) of alternative options. **- 2**

How can I "Navigate through terminal to the root director of this project" if I haven't even cloned the repository

- [ ] I could not reproduce the analysis because "go to http://localhost:8888 and navigate to the docs directory to use the project's notebook" is insufficient, it is missing the token or another more robust instruction. **- 3**

- [ ] I could not reproduce the analysis because there is no repository available inside the container. The docker command is probably missing a volume argument. **- 3**

- [ ] I could not reproduce the analysis because there is not git installed in the container to clone the original repository and no instructions for how to provide a password to install git. **- 3**

**Comment by alexkhadr** [comment]
Created src file in this commit https://github.com/DSCI-310/DSCI-310-Group-3/commit/b051f15a831ca0007bae7fb87cc63ee7af947630

**Comment by alexkhadr** [comment]
Fixed reproducibility due to [httin ](http://localhost:8888 )http://localhost:8888/ in commit https://github.com/DSCI-310/DSCI-310-Group-3/commit/0a1142b0ec5047dcbb3eaf3e725e4d5b2e447a4e

**Comment by rlaze** [comment]
Functions now check input and return error messages otherwise https://github.com/DSCI-310/DSCI-310-Group-3/commit/a56337247a8a9eb6e6c25aefc5e67f5183e331d5

Expanded on tests to check more input cases in https://github.com/DSCI-310/DSCI-310-Group-3/commit/bcb3eeed710fc5b4fe32eb4229ae868db4ae595f

**Comment by YellowPrawn** [comment]
There are cases of functions that do not check for proper input and/or do not provide useful error messages. - 3
-  https://github.com/DSCI-310/DSCI-310-Group-3/commit/4cfe46ca4e83d6f148188fbe8d1ba3ad5814961a
- https://github.com/DSCI-310/DSCI-310-Group-3/commit/bcb3eeed710fc5b4fe32eb4229ae868db4ae595f
- https://github.com/DSCI-310/DSCI-310-Group-3-Package/commit/0b4ea0b75b22047732fd06dd18331b14064b7331

There are some complex values that could be replaced by simpler values + some kind of expect_approximate test function. - 1
- https://github.com/DSCI-310/DSCI-310-Group-3/commit/27b22d45a1a0e6a79f3156ad8f1024c13ac9bc0e
- remark: this can only be accounted for via rounding due to the minor mathematical computation differences in chipsets

I ran the tests and got an error. ** - 3**
- https://github.com/DSCI-310/DSCI-310-Group-3/commit/27b22d45a1a0e6a79f3156ad8f1024c13ac9bc0e

There is no documentation. It is not clear what the tests are testing. - 5
- https://github.com/DSCI-310/DSCI-310-Group-3/commit/4cfe46ca4e83d6f148188fbe8d1ba3ad5814961a
- https://github.com/DSCI-310/DSCI-310-Group-3/commit/c4e71e2527ca7ec59d2f2a403b6e029ff9e1e576
- https://github.com/DSCI-310/DSCI-310-Group-3/commit/a49956fc8d2ce837a9cffae6a82dd8bd83a25f55
- https://github.com/DSCI-310/DSCI-310-Group-3/commit/bcb3eeed710fc5b4fe32eb4229ae868db4ae595f
- https://github.com/DSCI-310/DSCI-310-Group-3-Package/commit/0b4ea0b75b22047732fd06dd18331b14064b7331

There are cases of functions that do not test at least 2 expected input. - 0.5
- https://github.com/DSCI-310/DSCI-310-Group-3/commit/cc7b5f5cae1cc2525f2fb1b5b158131af1d3fda9

There are cases of functions that do not test at least 1 edge-case input. - 1
- https://github.com/DSCI-310/DSCI-310-Group-3/commit/cc7b5f5cae1cc2525f2fb1b5b158131af1d3fda9

There are cases of functions that do not test at least 1 wrong input. - 3
- https://github.com/DSCI-310/DSCI-310-Group-3/commit/4cfe46ca4e83d6f148188fbe8d1ba3ad5814961a
- https://github.com/DSCI-310/DSCI-310-Group-3/commit/cc7b5f5cae1cc2525f2fb1b5b158131af1d3fda9

**Comment by alexkhadr** [comment]
Fixed the "no repository available inside the container" issue in commit https://github.com/DSCI-310/DSCI-310-Group-3/commit/4df7c280be738a3c82c1c9bc25d0e1bc95072da2

**Comment by alexkhadr** [comment]
Added instructions about password in commit https://github.com/DSCI-310/DSCI-310-Group-3/commit/f95d563f4a33f1cffe2aba2f5fca86a8f6593a13
