### ISSUE TITLE
Milestone 1 feedback

### ISSUE THREAD

**Issue by GiuseppeTT** [DSCI-310/DSCI-310-Group-3#8]
*Congratulations on finishing milestone 1! We can see you put a lot of work into this project, nice work!
Below we list some specific feedback you can use to improve your project.
We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
If anything is unclear, please feel free to ask questions in this issue thread.*

### GitHub release

- [x] Please provide the link to the release as `https://github.com/DSCI-310/REPOSITORY/tree/VERSION`
(replacing `REPOSITORY` and `VERSION` with the correct ones for your project version for each milestone).
This makes is a lot easier for someone to just visit the repository as it was at that point in the project's history. **-1**

### README.md file

- [x] Summary in README should include high-level interpretation of analysis findings,
as well 1-2 sentences on what they might mean (at least at a high-level). **-1**
- [x] README should include include instructions on how to run the analysis. **-1**

### Analysis introduction

- [x] The project should be asking a predictive question.
See https://datasciencebook.ca/intro.html#asking-a-question and https://ubc-dsci.github.io/reproducible-and-trustworthy-workflows-for-data-science/materials/lectures/01-intro-to-ds-workflows.html#revisiting-the-definition-of-data-science-what-is-the-question
for clarification if needed. **-1**
- [x] The introduction should **identify** and **describe** the dataset that was used to answer the question. **-1**

### Analysis methods & results

- [x] The data should be reproducibly downloaded from it's source using code in the analysis code document,
and a copy saved in the `data` directory (and ideally in the `data/raw` subdirectory. **-1**
- [x] Narration of methods and method choices was not as clear and thorough as expected. **-1**
- [x] Plots suffer from one or more severe problems. For instance, overplotting, missing legend, small text or no axis labels. **-1**
- [x] All contributions are expected to go through code review via a pull-request. **-2**

### Analysis discussion

- [x] The discussion should not include new results. **-1**

### Dockerfile

- [x] The base image the `Dockerfile` uses in the `FROM` statement should have it's version pinned.
Failing to do this, means that each time the Docker image is built in the future,
the latest version of the base image will be used.
The latest version of the base image will very likely change over time,
and failing to do this will lead to the container not being able to be reproducibly built in the future. **-1**

### Project organization

- [x] The analysis notebook (`*.ipynb`) should be in a sub-directory called something sensible, such as `analysis`,
`src`, `notebooks`, `docs`, etc, to aid in the discoverability of this file, and related ones.
Having too many files in the project root makes the project organization less understandable
and can lead to longer activation times to productivity for collaborators (including future you!). **-1**

### GitHub Project board

- [x] Project board was not used for the entire duration of the milestone. **-1**
- [x] Project board is most effective when cards are converted to issues so that they can be assigned to collaborators, labelled and linked to milestones. **-1**

### GitHub Issue Milestones

- [x] GitHub issue milestones were not used. **-5**

### CONTRIBUTING.md

- [x] Contributing documentation should reflect all the ways people can contribute to the project
(core members, who should be working in a GitHub flow workflow involving branching in the main project repo and opening PR's,
as well as arms-length contributors, who more likely may have to fork the repo before submitting a PR). **-1**

### License

- [x] Creative commons license needs to be included to specify how non-code/software work can be used, shared and derived. **-2**

### Follows GitHub flow version control workflow

- [x] Project is expected to follow a GitHub flow version control workflow, which requires all branches to be divided into independent units of work (e.g., `feat-draft-analysis` for new feature which is the draft of the analysis, `fix-useage-docs` for some bug fix to the usage documentation) **-1**
- [x] All contributions are expected to go through code review via a pull-request. **-2**

###  Analysis can be run reproducibly using documentation provided in the README

- [x] Usage documentation could be improved for clarity (i.e., it is not explicitly clear to the user how to use the project, or some of the wording is confusing). **-2**
- [x] Clearly specify usage instructions to the point a user could copy and paste them and they would work.
If a specific value needs to be inserted (e.g., volume mounting, port forwarding, tag version - which should be specified, as relying on `latest` is unreliable for many reasons, etc)
suggest the most reasonable value and provide the list
(or link to a list) of alternative options. **-2**
- [x] Could not reproducibly run the analysis because there is no instructions. **-5**

**Comment by alexkhadr** [comment]
Complete

**Comment by rlaze** [comment]
Issues with workflows, Contributing, and Readme file fixed in this commit https://github.com/DSCI-310/DSCI-310-Group-3/commit/ef9e8a32422920184238a42647f531d17e2c2e4a

**Comment by rlaze** [comment]
Included code to download data here https://github.com/DSCI-310/DSCI-310-Group-3/commit/a394fe1446ea0533d0fbf03a10f9056e24b9f29e

Reformatted file structure here https://github.com/DSCI-310/DSCI-310-Group-3/commit/3c26c9c3a971f0b8faae4c4efa4bf14c7a4e94b6

Changes to github branches/project board use implemented around these commits
